### PR TITLE
Make tests pass on Python 3.2

### PR DESCRIPTION
**Pull request by msabramo**
Because colorclass already works on Python 3.2; it's just a matter of modifying the tests a bit so that they can show that.

### CODE REVIEW

**Comment by Robpol86** [comment]
I do not wish to support 3.2. To me it's like the 2.5 of 3.x. I presume all the other changes are required to get it working on 3.2 as well. I don't think the time I need to invest to make tests pass on 3.2 on all of my projects is worth it.

**Comment by msabramo** [comment]
Yeah. The only reason I consider python 3.2 is because pypy3 is python 3.2. But that's not a super compelling reason.

**Comment by Robpol86** [comment]
Ah I see. I'll consider supporting it in the future then. Probably in a few months once I'm done with libnl and wifipy.

**Comment by msabramo** [comment]
At some point, PyPy will presumably release a PyPy that implements 3.3 or 3.4, etc. So if you wait, it may become a non-issue.

**Pull request closed without merging**
